service: twitter-dollar-bot

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
    name: aws
    stage: ${opt:stage, 'dev'}
    runtime: nodejs10.x
    region: us-east-1

    environment: ${file(./.env/${self:provider.stage}.yml)}

    tracing:
        apiGateway: true
        lambda: true

    iamRoleStatements:
        - Effect: "Allow"
          Action:
              - "xray:PutTraceSegments"
              - "xray:PutTelemetryRecords"
          Resource:
              - "*"
plugins:
    - serverless-plugin-tracing

functions:
    tweetDollarJob:
        handler: functions/tweetDollar.job
        events:
            - schedule: cron(13 18 * * ? *)

    tweetDollarEndpoint:
        handler: functions/tweetDollar.endpoint
        events:
            - http:
                  path: ping
                  method: get
