service: twitter-dollar-bot

provider:
    name: aws
    stage: ${opt:stage, 'dev'}
    runtime: nodejs18.x
    region: us-east-1

    environment: ${file(./.env/${self:provider.stage}.yml)}

    lambdaHashingVersion: 20201221

    tracing:
        apiGateway: true
        lambda: true

plugins:
    - serverless-plugin-tracing

functions:
    tweetDollarJob:
        handler: functions/tweetDollar.job
        events:
            - schedule: cron(17 0 ? * MON-FRI *)

    tweetDollarEndpoint:
        handler: functions/tweetDollar.endpoint
        events:
            - http:
                  path: tweet
                  method: get
